version: "3.7"

services:
  pg-stocks:
    image: postgres

    environment:
      - POSTGRES_DB=stocks
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5433:5432

    networks:
      - techweek-net

  pg-products:
    image: postgres

    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432

    networks:
      - techweek-net

  # product-service:
  #   container_name: product-ms
  #   build:
  #     context: ./products

  #   ports:
  #     - 8082:8082

  #   depends_on:
  #     - pg-products
  #     - kafka

  #   environment:
  #     - DB_HOST=pg-products
  #     - DB_PORT=5432
  #     - DB_NAME=products
  #     - DB_USER=admin
  #     - DB_PASSWORD=postgres
  #     - KAFKA_SERVER=kafka:29092
  #     - KAFKA_TOPIC=live-products


  #   networks:
  #     - techweek-net

  pg-prices:
    image: postgres

    environment:
      - POSTGRES_DB=prices
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5434:5432

    networks:
      - techweek-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - techweek-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - techweek-net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - techweek-net
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  techweek-net:
    driver: bridge
